sixerr/sixerr/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^crazycats/', admin.site.urls),
    #url(r'^social/', include('social_django.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('sixerrapp.urls'))
]

sixerr/sixerrapp/urls.py
from django.conf.urls import url
from sixerrapp import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^overview/$', views.overview, name='overview'),
    url(r'^webhooks/$', views.webhooks, name='webhooks'),
    url(r'^privacy-policy/$', views.privacypolicy, name="privacypolicy"),
    url(r'^terms-of-use/$', views.termsofuse, name="termsofuse"),
    url(r'^connecthooks/$', views.connecthooks, name='connecthooks'),
    url(r'^gigs=(?P<id>[0-9A-Fa-f-]+)/$', views.gig_detail, name='gig_detail'),
    url(r'^my_gigs/$', views.my_gigs, name='my_gigs'),
    url(r'^create_gig/$', views.create_gig, name='create_gig'),
    url(r'^edit_gig/(?P<id>[0-9A-Fa-f-]+)/$', views.edit_gig, name='edit_gig'),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^validate_email/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                                    views.validate_email, name='validate_email'),
    url(r'^checkout/$', views.create_purchase, name='create_purchase'),
    url(r'^landingone/$',views.landing, name='landing'),
    #url(r'^create_purchase/$', views.create_purchase, name='create_purchase'),
    url(r'^my_sales/$', views.my_sales, name='my_sales'),
    url(r'^my_purchases/$', views.my_purchases, name='my_purchases'),
    url(r'^search/$',views.search, name='search'),
    #url(r'^purchases/(?P<id>[0-9A-Fa-f-]+)/$', views.transaction_detail, name='transaction_detail'),
    url(r'^sale=(?P<id>[0-9A-Fa-f-]+)/$', views.transaction_detail, name='transaction_detail'),
    url(r'^my_conversations/$', views.my_conversations, name='my_conversations'),
    url(r'^conversations/$', views.create_conversation, name='create_conversation'),
    url(r'^conversation=(?P<id>[0-9A-Fa-f-]+)/$', views.conversation_detail, name='conversation_detail'),
    url(r'^regions/$', views.get_country_data, name='get_country_data'),
    url(r'^stripe/$', views.create_purchase, name='create_purchase'),
    url(r'^taxes/$', views.get_tax_data, name='get_tax_data'),
    url(r'^(?P<link>[\w|-]+)/$', views.category, name='category')
]

sixerr/sixerrapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from django.conf import settings
from django.db.models import Lookup

# Custom lookup used in helpers.py by Chatentry and ConversationMsg
class NotEqual(Lookup):
    lookup_name = 'ne'

    def as_sql(self, compiler, connection):
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return '%s <> %s' % (lhs, rhs), params

from django.db.models.fields import Field
Field.register_lookup(NotEqual)

# Create your models here.

class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    displayname = models.CharField(max_length=150, null=True,blank=True, unique=True)
    avatar = models.CharField(max_length=500)
    about = models.TextField(max_length=2000, blank=True, null=True)
    slogan = models.CharField(max_length=500, blank = True, null=True)
    last_login = models.DateTimeField(default=timezone.now)
    avgstars = models.FloatField(blank=True, null=True)
    buystars = models.FloatField(blank=True, null=True)
    stripe = models.CharField(max_length=50,blank=True, null=True)
    striperefresh = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    zipcode = models.CharField(max_length=10, blank=True, null=True)
    country = models.CharField(max_length=2, blank=True, null=True)
    vanitymail = models.CharField(max_length=128, default="replace.me@roast.gg")
    emailoptin = models.BooleanField(default=True)
    emailverified = models.BooleanField(default=True)

    def __str__ (self):
        return self.user.username

class Ranking(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    # gamechoice=CATEGORY_CHOICES = (
    #     ("LL", "League of Legends"),
    #     ("OW", "Overwatch")
    # )
    # game = models.CharField(max_length=2, choices=gamechoice)
    owrankchoices = (("BR", "Bronze"), ("SV", "Silver"), ("GD", "Gold"),("PT", "Platinum"), ("DI", "Diamond"), ("MA", "Master"), ("GM", "Grandmaster"), ("UR", "Unranked"))
    lolrankchoices = (("BR", "Bronze"), ("SV", "Silver"), ("GD", "Gold"),("PT", "Platinum"), ("DI", "Diamond"), ("MA", "Master"), ("CH", "Challenger"), ("UR", "Unranked"))
    #rankchoices = (("BR", "Bronze"), ("SV", "Silver"), ("GD", "Gold"),("PT", "Platinum"), ("DI", "Diamond"), ("MA", "Master"), ("CH", "Challenger (League Of Legends)"), ("GM", "Grandmaster (Overwatch)"),("UR", "Unranked"))
    owusername = models.CharField(max_length=64, blank=True,null=True)
    owrank = models.CharField(max_length=2, blank=True,null=True, choices = owrankchoices)
    lolusername = models.CharField(max_length=64, blank=True,null=True)
    lolrank = models.CharField(max_length=2, choices= lolrankchoices, null=True,blank=True)

    def __str__(self):
        return self.user.username

class Gig(models.Model):
    CATEGORY_CHOICES = (
        ("LL", "League of Legends"),
        ("OW", "Overwatch")
        )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=500, validators=[MinLengthValidator(2,"length less than two")])
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)
    description = models.TextField(max_length=2000, validators=[MinLengthValidator(2,"length less than two")])
    price = models.IntegerField(default=6, validators=[ \
                    MinValueValidator(1,"minimum allowable $1"), \
                    MaxValueValidator(settings.MAX_GIG_PRICE,"more than max allowable price")])
    photo=models.CharField(max_length=250, blank=True) # clean_photo() injects placeholder
    status = models.BooleanField(default=True)
    user=models.ForeignKey(User)
    create_time = models.DateTimeField(default=timezone.now)
    boughttimes = models.IntegerField(default=0)
    sellmsg = models.TextField(max_length = 1000, blank=True, default='Please provide link to VOD')
    avgstars = models.FloatField(blank=True,null=True)

    def __str__ (self):
        return self.title

class Purchase(models.Model):
    STATUS_CHOICES = (
        ("OR","Purchased"),
        ("VS","VOD Received"),
        ("SS","Roast Delivered"),
        ("AC","Roast Accepted"),
        ("CO","Completed")
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    gig = models.ForeignKey(Gig)
    buyer = models.ForeignKey(User)
    time = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=2,choices=STATUS_CHOICES)
    title = models.CharField(max_length=500)
    category = models.CharField(max_length=50)
    description = models.TextField(max_length=2000)
    price = models.IntegerField(default=6)
    photo = models.CharField(max_length=250)
    stars = models.IntegerField(default = 0, blank=True, null=True,validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ])
    buystars = models.IntegerField(default=0, blank=True,null=True,validators=[MaxValueValidator(5), MinValueValidator(0)])
    taxamount = models.IntegerField(default=0)

    def __str__ (self):
        return self.gig.title

class Tempinfo(models.Model):
    user = models.ForeignKey(User)
    address1 = models.CharField(max_length=128)
    address2 = models.CharField(max_length=128,null=True,blank=True)
    zipcode = models.CharField(max_length=16)
    state = models.CharField(max_length=128)
    country = models.CharField(max_length=2)
    city = models.CharField(max_length=128)

class Review(models.Model):
    purchase = models.ForeignKey(Purchase)
    reviewer = models.ForeignKey(User, related_name = "reviewer")
    reviewee = models.ForeignKey(User, related_name = "reviewee")
    content = models.TextField(max_length = 2000)
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content

class Chatentry(models.Model):
    pid = models.ForeignKey(Purchase)
    poster = models.ForeignKey(User)
    content = models.TextField(max_length=2000)
    time = models.DateTimeField(default=timezone.now)
    read = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return self.content

class Conversation(models.Model):
    id = models.AutoField(primary_key=True)
    gig = models.ForeignKey(Gig, blank=True, null=True)
    sender = models.ForeignKey(User, related_name = "sender")
    receiver = models.ForeignKey(User, related_name = "receiver")
    starttime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.sender

class ConversationMsg(models.Model):
    id = models.AutoField(primary_key=True)
    parent = models.ForeignKey(Conversation)
    author = models.ForeignKey(User)
    content = models.TextField(max_length = 2000)
    read = models.BooleanField(blank=True, default=False)
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content

class Disconnectedhooks(models.Model):
    event = models.CharField(max_length=40, primary_key=True)

class Rankverify(models.Model):
    gamechoice=CATEGORY_CHOICES = (
        ("LL", "League of Legends"),
        ("OW", "Overwatch")
    )
    game = models.CharField(max_length=2, choices=gamechoice)
    user = models.ForeignKey(User)
    gameuser = models.CharField(max_length=64)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.gameuser

sixerr/sixerrapp/forms.py
from django.forms import ModelForm, ValidationError
from .models import Gig, Profile, Rankverify
# from django.core.exceptions import ValidationError
from django.conf import settings
import json
import re

# *******************
# Initialization code
# TODO: Find a better place for this code
# *******************

# Build 3 lists in memory
# 1 - countries - [ (code1, text1, regionlist1), ... ]
# 2 - available country codes (just for convenience) - [ code1, ... ]
# 3 - all regions by country [ {'country': code1, [ {'code': code1, 'text': text1}, ... ] }, ...]
STATES_DATA_PATH = 'sixerrapp/fixtures/states.json'
countries = []
available_country_codes = []
available_regions_per_country = {}
all_regions = []

with open(STATES_DATA_PATH, encoding='utf-8') as states_data_file:
    states_data = json.load(states_data_file)

for c in states_data['countries']:
    countries.append({'code': c['code'], 'text': c['text'], 'type': c['type']})
    # Make a list of available country codes just for convenience in Ajax validation
    available_country_codes.append(c['code'])
    regions = []
    just_region_values = [] # values are the region codes like 2-letter US states
    for r in c['regions']:
        regions.append({'value': r['value'], 'text': r['text']})
        just_region_values.append(r['value'])

    all_regions.append({'code': c['code'], 'type': c['type'], 'regions': regions})
    available_regions_per_country[c['code']] = just_region_values

# **************************
# End of initialization code
# ... continue with Forms
# *************************

class GigForm(ModelForm):
    class Meta:
        model = Gig
        fields = ['title', 'category', 'description', 'price', 'photo', 'status', 'sellmsg']

    # Validation for 'photo' field
    def clean_photo(self):
        data = self.cleaned_data['photo']

        # If empty, inject fixed placeholder image
        if not data:
            data = settings.MEDIA_PLACEHOLDER_IMAGE_PATH

        # Remember to always return the cleaned data.
        return data

    # Validation for 'status' field
    def clean_status(self):
        data = self.cleaned_data['status']

        # True only when select option value equal '1' otherwise False
        data = True if data == 1 else False

        # Remember to always return the cleaned data.
        return data

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['displayname', 'about', 'slogan', 'zipcode', 'state', 'country', 'emailoptin']

    # Validation for 'country' field
    def clean_country(self):
        data = self.cleaned_data['country']

        if data and data not in available_country_codes:
            raise ValidationError('Invalid value: %(value)s',
                                    code='invalid',
                                    params={'value': data})
            data = None

        # Remember to always return the cleaned data.
        return data

    # Validation for 'state' field
    def clean_state(self):
        data = self.cleaned_data['state']

        if 'country' in self.cleaned_data and self.cleaned_data['country'] == 'US':
            if data not in available_regions_per_country['US']:
                raise ValidationError('Invalid value: %(value)s',
                                        code='invalid',
                                        params={'value': data})
                data = None

        # Remember to always return the cleaned data.
        return data

    # Validation for 'zipcode' field
    def clean_zipcode(self):
        data = self.cleaned_data['zipcode']

        if 'country' in self.cleaned_data and self.cleaned_data['country'] == 'US':
            if not re.match(r'^\d{5}(?:[-\s]\d{4})?$', data):
                raise ValidationError('Invalid value: %(value)s',
                                        code='invalid',
                                        params={'value': data})
                data = None

        # Remember to always return the cleaned data.
        return data

class RankverifyForm(ModelForm):
    class Meta:
        model = Rankverify
        fields = ['game', 'gameuser']


class EmailVerifyForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['vanitymail', 'emailverified']

sixerr/sixerrapp/templates/commonTemplates/file_uploader_field.html
{% load template_settings %}

<div id="uploader"></div>
<input id="photoUploadedName" type="hidden" class="form-control" name="{{ fieldname }}" value="{% if instance %}{{ field }}{% endif %}" readonly>
<script>
  var originalPhotoUploadedName = document.getElementById("photoUploadedName").value
  var uploader = new qq.FineUploader({
//    debug: true,
    element: document.getElementById("uploader"),
    multiple: false, // just one file at a time
    validation: {
      allowedExtensions: ["jpeg", "jpg", "gif", "png", "tif", "tiff", "bmp"],
      itemLimit: 1,
      sizeLimit: 5 * 1024 *1024 // 5 megabytes
    },
    request: {
      endpoint: '{% settings_value "MEDIA_UPLOADER_ENDPOINT" %}'
    },
    deleteFile: {
      enabled: true,
      endpoint: '{% settings_value "MEDIA_UPLOADER_ENDPOINT" %}'
    },
    callbacks: {
      onDeleteComplete: function(id, xhr, isError) {
          if (!isError)
            document.getElementById("photoUploadedName")
              .setAttribute("value", originalPhotoUploadedName)
      },
      onComplete: function(id, name, responseJSON, xhr) {
          if (responseJSON.success)
            document.getElementById("photoUploadedName")
              .setAttribute("value", `${responseJSON.uuid}/${name}`)
      },
      onError: function(id, name, errorReason, xhrOrXdr) {
          alert(qq.format("Error on file number {} - {}.  Reason: {}", id, name, errorReason));
      }
    }
  })
</script>

sixerr/sixerrapp/templates/commonTemplates/gigsThumbnail.html
{% load staticfiles %}
{% load template_settings %}

{% for gig in gigs %}
<div class="col-md-3">
  <div class="thumbnail{% if not gig.status %} disabled-overlay{% endif %}">
    {% if overlayEnabled and canNotPublishGig %}
    <div class="overlay">
      <ul>
        {% if noCompleteBillingCountry %}
        <li><p>Missing country in <strong><a href="{% url 'profile' user.profile.displayname %}">My Profile</a></strong>.</p></li>
        {% endif %}
        {% if noStripeAccountYet %}
        <li><p>No connected account to pay you</p>
          <a href="{% url 'social:begin' 'stripe'%}?next={{request.path}}"><img src="{% static 'img/blue-on-light@2x.png'%}"></a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
    <a href="{% url 'gig_detail' gig.id %}"><img src="{% settings_value "MEDIA_ROOT" %}{{ gig.photo }}" ></a>
    <div class="caption">
      <p><a href="{% url 'gig_detail' gig.id %}">{{ gig.title }}</a></p>
      <p><span>by <a href={% url 'profile' gig.user.profile.displayname %}>{{ gig.user.profile.displayname }}</a></span></p>
      <b class="dollar green pull-right">{{ gig.price }}</b>
      {% if gig.avgstars %}
      <div class="pull-left">
      <label class="glyphicon glyphicon-star"></label><font color="gray">({{ gig.avgstars }})</font>
      </div>
      {% endif %}
      {% if gig.category == 'OW' and gig.user.ranking and gig.user.ranking.owrank %}
      <img class="verified-rank" src="{% static 'img/verified.png' %}">{{ gig.user.ranking.get_owrank_display }}
      {% endif %}
      {% if gig.category == 'LL' and gig.user.ranking and gig.user.ranking.lolrank %}
      <img class="verified-rank" src="{% static 'img/verified.png' %}">{{ gig.user.ranking.get_lolrank_display }}
      {% endif %}
      <br>
    </div>

  </div>
</div>
{% endfor %}

sixerr/sixerrapp/templates/commonTemplates/uploader_setup.html
{% load staticfiles %}

    <link href="{% static 'css/fine-uploader-gallery.css' %}" rel="stylesheet">
    <script src="{% static 'js/fine-uploader.min.js' %}"></script>
    <script type="text/template" id="qq-template">
        <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Click upload button or drop image here">
            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span class="qq-upload-drop-area-text-selector"></span>
            </div>
            <div class="qq-upload-button-selector qq-upload-button">
                <div>Upload image</div>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped image...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
                <li>
                    <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                    <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <div class="qq-thumbnail-wrapper">
                        <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
                    </div>
                    <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
                    <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                        <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                        Retry
                    </button>

                    <div class="qq-file-info">
                        <div class="qq-file-name">
                            <span class="qq-upload-file-selector qq-upload-file"></span>
                            <span class="qq-edit-filename-icon-selector qq-btn qq-edit-filename-icon" aria-label="Edit filename"></span>
                        </div>
                        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                        <span class="qq-upload-size-selector qq-upload-size"></span>
                        <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                            <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                            <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                            <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                        </button>
                    </div>
                </li>
            </ul>

            <dialog class="qq-alert-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Close</button>
                </div>
            </dialog>

            <dialog class="qq-confirm-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">No</button>
                    <button type="button" class="qq-ok-button-selector">Yes</button>
                </div>
            </dialog>

            <dialog class="qq-prompt-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <input type="text">
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cancel</button>
                    <button type="button" class="qq-ok-button-selector">Ok</button>
                </div>
            </dialog>
        </div>
    </script>